# Generated by Django 6.0.2 on 2026-03-13 06:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SELLER', 'Seller'), ('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('SELLER_STAFF', 'Seller staff')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='SellerStaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_view', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='account.sellerprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
