# Generated by Django 6.0.2 on 2026-02-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
